title: AulaTaller
description: Blog para usar en el aula

url: "https://alvarmaciel.github.io"
baseurl: "/aula-taller"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: alvarmaciel
   twitter: amaciel
   facebook: 
   email: alvarmaciel@gmail.com

highlighter: pygments
github: [Repository metadata]

#google_analytics: "UA-58263416-1"
