# Site settings
title: AulaTaller
email: alvarmaciel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog para usar en las aulas.
baseurl: "/aula-taller" # the subpath of your site, e.g. /blog/
url: "http://alvarmaciel.github.io" # the base hostname & protocol for your site
twitter_username: amaciel
github_username:  alvarmaciel

# Build settings
markdown: kramdown
